# docker-compose.yml
version: "3.8"
services:
  nginx:
    container_name: nginx
    build: ./docker/nginx
    command: nginx -g "daemon off;"
    links:
      - php
    ports:
      - "80:80"
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./src:/var/www/html
  php:
    container_name: php
    env_file:
      - ./src/.env
    build: ./docker/php
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html

  mysql:
    image: mysql:8.0.32
    container_name: mysql
    env_file:
      - ./env/mysql.env
    ports:
      - "3306:3306"
    volumes:
      - ./database/mysql:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8085:80
